name: flight_tracker
description: A flight tracking & delay prediction app similar to Flighty.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  barcode_widget: ^2.0.4
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^14.1.1
  flutter_map: ^4.0.0
  flutter_svg: ^2.0.6
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  latlong2: ^0.8.1
  path_provider: ^2.0.15
  purchases_flutter: ^8.7.0
  shared_preferences: ^2.1.1
  supabase_flutter: ^1.10.4
  timeago: ^3.4.0
  timezone: ^0.9.0
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
